# Development-specific configuration overrides

# Server configuration
# Development-specific overrides
environment = "development"
frontend_url = "http://localhost:3000"

# Database configuration
database_url = "postgres://localhost:5432/books"

# ML Model configuration
model_path = "apps/api/models"
sentence_transformer_model = "all-mpnet-base-v2"
max_sequence_length = 512

# Security
# WARNING: These are for development only. In production, use secure keys.
api_key = "dev-secret-key"

# Pinecone configuration
# These should be overridden with environment variables in development
pinecone_api_key = "your_api_key"
pinecone_environment = "your_environment_name"
pinecone_index = "your_index_name"

# HuggingFace configuration
# This should be overridden with environment variables in development
huggingface_api_key = "your_api_key"

# Logging configuration
log_level = "debug"
