services:
  - type: web
    name: recommend-a-book-rust-api
    runtime: rust
    region: frankfurt
    plan: starter
    buildCommand: cargo build --release
    startCommand: |
      curl -s http://localhost:10000/api/prewarm &
      ./target/release/recommend-a-book-api
    healthCheckPath: /api/prewarm
    envVars:
      - key: RUST_LOG
        value: info
      # Optimize for faster cold starts
      - key: ROCKET_WORKERS
        value: "2"
      - key: RUN_MODE
        value: production
      - key: APP_HOST
        value: 0.0.0.0
      - key: APP_PORT
        value: 10000
      # IMPORTANT: Make sure to set RUST_LOG to at least "info" to see important configuration messages
      - key: APP_ENVIRONMENT
        value: production
      # Prewarming configuration to mitigate cold starts
      - key: APP_ENABLE_PREWARM
        value: "true"
      - key: APP_PREWARM_TIMEOUT_SECS
        value: "30"
      - key: APP_FRONTEND_URL
        value: https://recommend-a-book-frontend.vercel.app
      # Database configuration
      - key: APP_DATABASE_URL
        value: postgres://localhost:5432/books
      # Supabase configuration - REQUIRED, must be set via Render dashboard
      - key: APP_SUPABASE_URL  # Your Supabase project URL
        sync: false
      - key: APP_SUPABASE_KEY  # Your Supabase API key
        sync: false
      # Pinecone configuration - REQUIRED, must be set via Render dashboard
      # These values must be set correctly for the API to function
      - key: APP_PINECONE_API_KEY  # Your Pinecone API key (from Pinecone dashboard)
        sync: false
      - key: APP_PINECONE_ENV  # Pinecone environment (e.g., "gcp-starter" or "us-west1-gcp")
        sync: false
      - key: APP_PINECONE_INDEX_NAME  # Name of your Pinecone index (without -project suffix)
        sync: false
      # HuggingFace API key for ML models (optional, only needed if using HuggingFace embeddings)
      - key: APP_HUGGINGFACE_API_KEY
        sync: false
    autoDeploy: true
    repo: https://github.com/hari2309s/recommend-a-book
    rootDir: apps/api
    buildFilter:
      paths:
        - apps/api/**/*
      ignoredPaths:
        - apps/api/target/**/*
