services:
  - type: web
    name: recommend-a-book-api
    runtime: rust
    buildCommand: cargo build --release
    startCommand: ./target/release/recommend-a-book-api
    envVars:
      - key: RUST_LOG
        value: info
      - key: HOST
        value: 0.0.0.0
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: PINECONE_API_KEY
        sync: false
      - key: PINECONE_ENVIRONMENT
        sync: false
      - key: PINECONE_INDEX
        sync: false
      - key: HUGGINGFACE_API_KEY
        sync: false
      - key: PORT
        value: 3000
    autoDeploy: true
    healthCheckPath: /health
    numInstances:
      min: 1
      max: 1
    github:
      branch: main
    buildFilter:
      paths:
        - apps/api/**/*
