services:
  - type: web
    name: recommend-a-book-rust-api
    runtime: rust
    region: frankfurt
    plan: starter
    buildCommand: cargo build --release
    startCommand: ./target/release/recommend-a-book-api
    healthCheckPath: /health
    envVars:
      - key: RUST_LOG
        value: info
      - key: RUN_MODE
        value: production
      - key: APP_HOST
        value: 0.0.0.0
      - key: APP_PORT
        value: 10000
      - key: APP_ENVIRONMENT
        value: production
      - key: APP_FRONTEND_URL
        value: https://recommend-a-book-frontend.vercel.app
      # Database configuration
      - key: APP_DATABASE_URL
        value: postgres://localhost:5432/books
      # Supabase configuration (set via Render dashboard)
      - key: APP_SUPABASE_URL
        sync: false
      - key: APP_SUPABASE_KEY
        sync: false
      # Pinecone configuration (set via Render dashboard)
      - key: APP_PINECONE_API_KEY
        sync: false
      - key: APP_PINECONE_ENVIRONMENT
        sync: false
      - key: APP_PINECONE_INDEX
        sync: false
      # HuggingFace API key for ML models (optional)
      - key: APP_HUGGINGFACE_API_KEY
        sync: false
    autoDeploy: true
    repo: https://github.com/hari2309s/recommend-a-book
    rootDir: apps/api
    buildFilter:
      paths:
        - apps/api/**/*
      ignoredPaths:
        - apps/api/target/**/*
